apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: tax-calculator-pipelinerun
spec:
  pipelineRef:
    name: tax-calculator-pipeline
  params:
    - name: repo-url
      value: https://github.com/fbritoferreira/travel-recommendations
    - name: image
      value: us.icr.io/cloud-native-final/tax-calculator:1
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
